# Site settings
title: Joseph Martinsen
author_name: Joseph Martinsen
email:
description: Joseph Martinsen Personal Website

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://joseph.martinsen.com" # the base hostname & protocol for your site

# Tags
photoTag: "Photography"

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/nbahoopstar05
  - title: facebook
    url: https://www.facebook.com/joseph.martinsen
  - title: google-plus
    url: https://google.com/+JosephMartinsen
  - title: github
    url: https://github.com/JosephMart
  - title: linkedin
    url: https://www.linkedin.com/in/joseph-martinsen/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","gulpfile.babel.js","package.json","README.md", "yarn.lock", "LICENSE"]
plugins: [jekyll-paginate, jekyll-feed]
